index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction # initialisation de la nouvelle page d'accueil
  defaults:
    template: 'home.html.twig'

home:
  path: /home
  controller: App\Controller\ApiRestfulController::index

get:
  path: /users_infos
  defaults: { _controller: App\Controller\UsersController::getUserAction, _format: json }


post:
  path: /user_info
  defaults: { _controller: App\Controller\UsersController::postUserInfoAction, _format: json }

hp:
  path: /hp
  defaults: { _controller: App\Controller\Users::index }

form:
  path: /form
  defaults: { _controller: App\Controller\UsersController::form_IMC }

success:
  path: /form/success
  defaults: { _controller: App\Controller\UsersController::success }

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# If you also want to expose it in JSON
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }


