#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
   path: /home
   controller: App\Controller\ApiRestfulController::index

get:
   path: /users_infos
   defaults: { _controller: App\Controller\ApiRestfulController::getUserInfoAction, _format: json }

post:
   path: /user_info
   defaults: { _controller: App\Controller\ApiRestfulController::postUserInfoAction, _format: json }

